### ISSUE TITLE
处理后的RCV1-V2或EURLEX数据集

### ISSUE THREAD

**Issue by farisxiong** [qianlima-lab/HiMatch#1]
可以分享一下处理后的RCV1-V2或EURLEX数据集吗，没有整明白怎么对多层次的数据集处理。

**Comment by haibin-chen** [comment]
你好！这里是EURLEX数据集：https://drive.google.com/file/d/1s_xOTiMv3OtETdiSV7BH0V9LLg-XFZYQ/view?usp=sharing。RCV数据集需要按readme的链接申请使用权限后，我才能发给你 : )

**Comment by hnustpangrui** [comment]
大佬你好，请问一下，如果我通过了RCV1-V2的使用权限，您会给我发一份清洗过的可用的RCV1-V2数据集吗？
